### PR TITLE
Solved crafting count output. Protection radius increase by 2.

### PR DESCRIPTION
**Pull request by rredesigns**
Fix to reported issue in MFF-SB issues page. Plus a little upgrade to protections.

### CODE REVIEW

**Comment by Lymkwi** [comment]
Okay. So the amount of locks is back to normal. Although, did we say we would increase the amount of normal protectors crafter? I think we did but we didn't discuss about that with @Ombridride. He should give his opinion. (Apart from that the commits are okay)

**Comment by BetterToAutomateTheWorld** [comment]
4 per 4 (normal) protector block : it's ok and a good idea

The new super_protector_block should be added later, and with an another craft recipe, it's a unic new node, and we don't need to increase the protection of the normal protector block

**Comment by rredesigns** [comment]
Doesn't matter. Gravgun already commited the same fix, so this issue is actually fixed from about a day ago. You can close it now.

**Comment by Lymkwi** [comment]
Still thanks for that pull request.

**Pull request closed without merging**
